### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by duclet** [axllent/silverstripe-simplemde-markdown#1]
The CSS and JS for the editor lives in /vendor. However, the .htaccess file (default ones anyway), explicitly blocks directly linking to that. As such, the editor won't load.

**Comment by axllent** [comment]
Good catch! I don't use the standard SilverStripe `.htaccess` so I hadn't realised that!

I'd prefer not to have to package simplemde directly into this module (ie: for simplemde updates etc). Do you have any idea if it's possible to specify that a package's requirements should go into a directory other that into `/vendor? I've been looking but can't find a working solution.

**Comment by duclet** [comment]
Ideally, it would be nice if we could have done this through the `composer/installers` package. However, it seems like that isn't possible unless the following happens:
- There is a custom installer that installs with the default installation locations.
- The SimpleMDE package gets updated to use the above custom installer.
- We override the location in the `custom.json`

I've seen other modules include frontend dependencies by just including them but I see that you are against it. I don't fully like it either but I can't say I like including dependencies with the wildcard (`*`) since that could break in the future if the dependency contains a backward incompatible change. But that is a whole different topic (issue?)

That pretty much just leaves one option, updating the `.htaccess` to allow access to the files. I wouldn't allow access to every file but I think access to JavaScript and CSS files should be okay. As such, probably add to the `README.md` that the user would need to add the following line:

```
        RewriteCond %{REQUEST_FILENAME} !\.(js|css)$   
```

above this line:

```
        RewriteRule ^vendor(/|$) - [F,L,NC]
```

So that the `.htaccess` file would look similar to the following:

```
...
        # Deny access to potentially sensitive files and folders
        RewriteCond %{REQUEST_FILENAME} !\.(js|css)$   
        RewriteRule ^vendor(/|$) - [F,L,NC]

        RewriteRule silverstripe-cache(/|$) - [F,L,NC]
        RewriteRule composer\.(json|lock) - [F,L,NC]
...
```
