### ISSUE TITLE
Add linking ability for internal pages

### ISSUE THREAD

**Issue by duclet** [axllent/silverstripe-simplemde-markdown#2]
It would be nice to have the ability when creating a link, a HTML shows up with references to all the pages that is available so one can select and link to it rather than typing it in manually. The following project have such a functionality:

https://github.com/MadeHQ/silverstripe-markdown

**Comment by axllent** [comment]
Very nice (I just had a play), but it seems MadeHQ has pretty much had to rewrite the entire `LinkDialog` for SilverStripe to get that partially working ([see this](https://github.com/MadeHQ/silverstripe-markdown/blob/master/javascript/MarkdownEditorField.js)). There also seem to be some issues with those modifications (eg: insert image doesn't work) which may already be the result of SilverStripe changes.

The downside is _if & when_ SilverStripe change their file dialogue structure / code, it is going to break this one, and so I don't plan to replicate or maintain this for something I don't personally use. There may be an easier & better way to integrate with it though, but I don't have time unfortunately to look into it.

Again, a great feature request, and if you're willing to find a more reliable/maintainable method and create a pull request with the code then I'd gladly integrate it ;-) It may however be easier to use `mademedia/silverstripe-markdown` and modify that to your requirements?

**Comment by duclet** [comment]
Yes, it is a lot of work. I think at a minimum, what I really care for the linking between pages, rather than images and the like. This is something I would like add so can you leave this issue open so I or someone else can work on it (I like keeping it open so I don't forget about it)? Thanks.

**Comment by axllent** [comment]
Fair enough, you're totally right so not a problem. I read a post yesterday that announced the [new file manager for SilverStripe v4](http://www.silverstripe.org/blog/silverstripe-4-0-changes-to-files/) which I think proves my point. 

If somebody is going to implement this however then i think it would be best to include both SiteTree links as well as assets though.
